FROM node:16
EXPOSE 3000
RUN mkdir -p /app/config /app/src
WORKDIR /app
COPY ormconfig.json /app/ormconfig.json
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
COPY tsconfig.json /app/tsconfig.json
CMD npm install && npm run typeorm migration:run && npm start