FROM node:16
EXPOSE 3000
RUN mkdir -p /app/config /app/src
WORKDIR /app
COPY ormconfig.json /app/ormconfig.json
COPY package.json /app/package.json
COPY tsconfig.json /app/tsconfig.json
RUN npm install
RUN npm run typeorm migration:run
CMD ["npm", "run", "typeorm", "migration:run"]
CMD ["npm", "start"]