FROM node:16
EXPOSE 3002
RUN mkdir -p /app/public /app/src
WORKDIR /app
COPY index.html /app/index.html
COPY jsconfig.json /app/jsconfig.json
COPY netlify.toml /app/netlify.toml
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
COPY postcss.config.js /app/postcss.config.js
COPY tailwind.config.js /app/tailwind.config.js
COPY vite.config.js /app/vite.config.js
RUN npm install
CMD ["npm", "run", "dev"]