FROM node:16
EXPOSE 3000
RUN mkdir -p /app/public /app/src
WORKDIR /app
COPY index.html /app/index.html
COPY package.json /app/package.json
COPY postcss.config.js /app/postcss.config.js
COPY tailwind.config.js /app/tailwind.config.js
COPY tsconfig.json /app/tsconfig.json
COPY vite.config.ts /app/vite.config.ts
RUN npm install
CMD ["npm", "run", "dev"]